#+TITLE: MuxParse Notes
#+AUTHOR: Calvin Beck
#+OPTIONS: ^:{}

* Overview
  This is a library / file specification for Arduino networking
  hubs. It's designed to be used with the MuxDuino library, which is
  used to turn an Arduino into a little networking hub by redirecting
  various pins (it sends the inputs from one pin to another pin).

  We will call the files that we are parsing ".mux" files and the
  specification is pretty simple. This library will allow you to fetch
  each of the MuxDuino pipes in the file one by one. This parser may
  be adapted to work with Arduinos and SD cards if you just want to
  put the ".mux" file on an SD card or something, however this
  currently uses the unix file handling stuff in stdio.h.

  This library will be used to actually generate an Arduino program
  which uses the MuxDuino library given a certain network topology in
  a ".mux" file. This is useful if you don't want to waste your
  precious Arduino pins on an SD card reader, but still want to have
  configureable networks!

* File Description
  The ".mux" files consist of a sequence of entries. Each entry
  represents a single MuxPipe from the MuxDuino library. Each entry
  consists of three integers. The first integer is the *in_pin*, the
  second is the *out_pin*, and the third is the *channel*. Each of
  these integers must be separated by some kind of whitespace. At the
  end of each entry there must be a semi-colon.

  In addition to that we also support line comments which start with
  the '#' character. After '#' is spotted the rest of the line is
  ignored by the parser. This allows you to label different pieces of
  your network so it's easier to understand later. Here is an example
  of how this might work:

  #+BEGIN_EXAMPLE
    # An input on pin 12 is written to the output pin 13 on channel 0.
    12 13 0;
  #+END_EXAMPLE

* Interface
  There is only one function exposed by the MuxParse library.

  #+BEGIN_SRC c
    int mux_parse_pipe(FILE *mux_file, MuxPipe *pipe);
  #+END_SRC

  This function takes as arguments a file pointer (for the ".mux" file
  you want to parse), and a pointer to a MuxPipe structure where the
  results are to be stored.

  A return value of 0 means that the function has returned succesfully
  and there is a new set of values stored in the location pointed to
  by *pipe*. If this returns 1 then that just means the end of the
  file has been reached, and no new pipes have been found. However, if
  2 is returned it means that some parsing error was encountered.

  In order to parse a file *mux_parse_pipe()* must be called over and
  over, reading in a single pipe at a time until it returns a value
  of 1. Each time a pipe is retrieved it may be registered MuxDuino,
  printed for information, or whatever.
